from PIL import Image, ImageEnhance
import ascii_magic
import turtle

def main():
    # 1. HARDCODED PATH: Replace this with your complete image file path
    # image_path = r"C:\Users\anuka\Downloads\images.jpg"
    image_path = r"C:\Users\anuka\Downloads\DSC_4596 (1) (2).jpg"

    try:
        # 2. Open image and apply moderate contrast
        img = Image.open(image_path)
        img = ImageEnhance.Contrast(img).enhance(1.3)

        # 3. Set a smaller width for turtle rendering to keep it readable and fast
        columns_to_use = 80

        # 4. Load the pre-processed image for ASCII text generation
        my_art = ascii_magic.AsciiArt.from_pillow_image(img)

        # 5. Moderate character ramp optimized for dark backgrounds
        moderate_ramp = " .:-=+*#%@$"

        # 6. Generate the monochrome text art strings
        wood_text = my_art.to_ascii(
            columns=columns_to_use,
            char=moderate_ramp,
            monochrome=True
        )
        
        # 7. Split into individual lines for turtle processing
        text_lines = wood_text.splitlines()
        
        # 8. NEW: Create a small version of the image to extract colors per line
        # Total rows matches the number of lines generated by ascii_magic
        rows_to_use = len(text_lines)
        color_img = img.resize((columns_to_use, rows_to_use)).convert("RGB")
        
        # 9. Set up the Turtle Screen
        screen = turtle.Screen()
        screen.setup(width=900, height=700)
        # screen.setup(width=1080, height=1900)
        screen.bgcolor("black")  
        screen.title("ASCII Art Turtle Animation")
        screen.colormode(255)  # Enables RGB color codes (0-255) instead of just string names
        screen.tracer(0)

        # 10. Set up the Drawing Turtle
        t = turtle.Turtle()
        t.hideturtle()
        t.penup()

        # 11. Animation Loop with Color Extraction
        start_y = 300  
        line_height = 14  

        for i, line in enumerate(text_lines):
            t.goto(-400, start_y - (i * line_height))
            
            # OPTION A: Extract a single average color for the entire line (Faster rendering)
            # We sample the middle pixel of the row from our resized color image
            middle_column = columns_to_use // 2
            pixel_color = color_img.getpixel((middle_column, i))
            
            # Apply the sampled RGB color to the turtle pen
            t.color(pixel_color)
            
            # Write the complete row text in that color
            t.write(line, move=False, align="left", font=("Courier", 10, "bold"))
            screen.update()

        screen.update()
        print("Rendering complete with image colors!")
        screen.mainloop()  

    except FileNotFoundError:
        print(f"Error: The file '{image_path}' could not be found. Please check your path spelling.")
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    main()
